apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-webhook
  labels:
    app: validate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validate
  template:
    metadata:
      labels:
        app: validate
    spec:
      containers:
      - name: webhook
        image: kmitevski/webhook:gunicorn
        ports:
        - containerPort: 443
        env:
        - name: LABEL
          value: development
        volumeMounts:
        - name: certs-volume
          readOnly: true
          mountPath: "/certs"
        imagePullPolicy: Always
      volumes:
      - name: certs-volume
        secret:
          secretName: admission-tls
---
apiVersion: v1
kind: Service
metadata:
  name: validate
spec:
  selector:
    app: validate
  ports:
  - port: 443
---
apiVersion: v1
kind: Secret
metadata:
  name: admission-tls
type: Opaque
data:
  webhook.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVHakNDQXdLZ0F3SUJBZ0lVY1hUWmRiZHdCQjB3d0ZqeGdoZElLSEFDK21zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZc3hDekFKQmdOVkJBWVRBa2xPTVFzd0NRWURWUVFJREFKTFFURVFNQTRHQTFVRUJ3d0hWVTVMVGs5WApUakVOTUFzR0ExVUVDZ3dFVTBWTVJqRU5NQXNHQTFVRUN3d0VVMFZNUmpFV01CUUdBMVVFQXd3TloyOTJhVzVrCllYSmhhbUZ1ZGpFbk1DVUdDU3FHU0liM0RRRUpBUllZWjI5MmFXNWtZWEpoYW1GdWRrQm5hWFJvZFdJdVkyOXQKTUI0WERUSXpNVEF3T0RFeU1qSTFPVm9YRFRJMk1EY3lPREV5TWpJMU9Wb3dnWXN4Q3pBSkJnTlZCQVlUQWtsTwpNUXN3Q1FZRFZRUUlEQUpMUVRFUU1BNEdBMVVFQnd3SFZVNUxUazlYVGpFTk1Bc0dBMVVFQ2d3RVUwVk1SakVOCk1Bc0dBMVVFQ3d3RVUwVk1SakVXTUJRR0ExVUVBd3dOWjI5MmFXNWtZWEpoYW1GdWRqRW5NQ1VHQ1NxR1NJYjMKRFFFSkFSWVlaMjkyYVc1a1lYSmhhbUZ1ZGtCbmFYUm9kV0l1WTI5dE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXJGU2doSDBvQ3ZLdVFLUWIrWjFmOTJFazIvM0F5NTFzR0xKQmRCMnROVXhFCjNWWkQ4YjM4UVRpSU5NRmtNWjFhbjhqdUtCeGw4NmJBNEpJdDVPTzJFbXJRR1JpWk44UjZSbE52OUFvK2ovdVAKb1B1TWs3ZjAxRDQrVGZld2pOZUJZWW1RNHNMMTZCS3QyWWlROHoyekFCeHBvcGhPbEkyczE1Nm5JSzJhQkdLUwp1SVYxcERkdC9xbTcxTzZ0N2tKajVDalN2MmZMNGxJZmNwTk5PT1MvQlRGZlpwQmwxK21waEVYK0dJL3g5ZWo0CkIxMlBYTUtYaVdWSEMxRzY4cUZHOEpjNVpUbldndkN3UTJPRFRtVWNzdGxwc0U1Wnp4SDdzUlpXZ1d3TVBRVEsKUGFqcTVVVXhScHdYNXMwS09SSlNuQWw1UnNEK21qQmN0VUY1R2NKWDFRSURBUUFCbzNRd2NqQWRCZ05WSFE0RQpGZ1FVaUVzNkFiWXBPbExzTUxadWpubkVZMGFTRzA0d0h3WURWUjBqQkJnd0ZvQVVpRXM2QWJZcE9sTHNNTFp1CmpubkVZMGFTRzA0d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZkJnTlZIUkVFR0RBV2doUjJZV3hwWkdGMFpTNWsKWldaaGRXeDBMbk4yWXpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQXBNRmtQK1gyMjNTeHVFZEQrRGNqcGtTQwptNmhYNjAyMnNDT1UvdHFIY0N1MVl5NWhMUUNCTFBNTnZyZFozKzFkK05PamhYcFUzQ01mL2Vtd0xNQUFYWDlVClhBLzJEd1BhLzIzbk4vbE5BTGhlWkZoZ3lPUmJOZTlZUHVmeDh2UDRHWWs4V1cxcnV0V3V3Mnd6cTVBM0dJSmEKQWV5VXZyZHZnc2xwZVNxSlNNNWx4OFl5dXZGZFo0REMveis1QzZxd3dZZnFuV1FZelNSZThmeVNCNjZCT0VweQpkazR1MUFJYVFmYzgrZnExbHVDa1FIUzZnOWRsSDd2RGFBbGp2cVR2dzJyUTdrRXQ4bkE4cWNnMkdiL3NVb0s3Cm53WlBUVU1ZUWZXZS9VcTRRWTJ2NFJWRzVsSGc0SUFLMWZ2c3NyTStaSEZPam8vNHoxSTVud2R1czI4b3NRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  webhook.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQ3NWS0NFZlNnSzhxNUEKcEJ2NW5WLzNZU1RiL2NETG5Xd1lza0YwSGEwMVRFVGRWa1B4dmZ4Qk9JZzB3V1F4blZxZnlPNG9IR1h6cHNEZwpraTNrNDdZU2F0QVpHSmszeEhwR1UyLzBDajZQKzQrZys0eVR0L1RVUGo1Tjk3Q00xNEZoaVpEaXd2WG9FcTNaCmlKRHpQYk1BSEdtaW1FNlVqYXpYbnFjZ3Jab0VZcEs0aFhXa04yMytxYnZVN3EzdVFtUGtLTksvWjh2aVVoOXkKazAwNDVMOEZNVjlta0dYWDZhbUVSZjRZai9IMTZQZ0hYWTljd3BlSlpVY0xVYnJ5b1Vid2x6bGxPZGFDOExCRApZNE5PWlJ5eTJXbXdUbG5QRWZ1eEZsYUJiQXc5Qk1vOXFPcmxSVEZHbkJmbXpRbzVFbEtjQ1hsR3dQNmFNRnkxClFYa1p3bGZWQWdNQkFBRUNnZ0VBUjdUM0Rlb2VMV0FKemUvN2pBUkdHR09kdU1SLzRybmdidTVOZWdtWE55UkQKUzI1SDIyRllnN01JU2h0bW01YUVUUlNJdEx3TVdEUTg4YlVoejZwSTZxVHpibDNqODJhWUVvZEpnRng2NStLZgpRemNvcVpiVUV6VExMQm95cG9oTjE4NHNNWTg2VDVUbUxpdzdWRnVLRGpQRWFObkRhT0VDMkwyMWdVMTdWdk1WCnkwNEZIMSs4YVNKYiszUFRoM2Y0Q1lZL2cvNXNweUNtbFk2ZDViUjVQRmVVdzBVbVNUS25EUUZiUVNReDl3cXMKR1ptaHhocm9ZN0QwZW1LRk9zRG1ja0VodTV0ZTNTNUhOZ3VYdzdGWjMxWVY1Z01Za1FMQzAzdkFxQVRnYWc5TgpOVU1PVnNjNTZtN0w1SXVmM1FsVmZncU53QzVCVThxSGVrSDd5R1piaVFLQmdRRG5ObVc1QkZ2bzlPYy9oWTVjCm96eHI2Y3hjRFVlTm9nMm1zcDNKQkZGRGJpUC8wenZvNkhhSFJLcXZsK29JMW1rYS91MGlrQ3FQMFVMUFVwOUcKWWZoUEp6UURTUFFnT25TM3NJNVJTdmtzaGU0NSt5U2RYZk5ybHFhRG5mc3d4M0RPeTFIc25tK1VaT1ZwY1ZlYwpJMGEwRFZpdDQxYVFKZGlXT3pDT2ZWN2R6d0tCZ1FDK3pqaTl5MUJsdTA5Rk9iRlN5RzE3SlhkbGRUaEFKc3ZKCmpuQUMwb2RKOE5QZmp1R1JzbzJNVk9UWXdpM0I5eElKVndRVVFmMG1GNG1peDN1S25TNlBvVFpwOFIzVVBrS0QKNGZHcERnNkVUakJTNlFlVUhKbUY5bDA4S2NiMDBOaldlUlBnS2E0OEZIVFFvc2xld2lQOVEvSXd4SUNYUUtmegp5dlJxVVBlZEd3S0JnRGlRWFVocklaVVhQTytVVytTYjVxODd6a3dDejZ0OXBydE9YVDJOT2RnMlBNWmNSZjdQCnlCZUZuQUJET1BVYWh6SWNoYVQ4QWYyWEl6SVhNM0lEaTd6SmlYYjRSUWtSWS9hQVVnRGZSNkExejdjTmtzS1EKOW5rdXJPUHNKVVNrdGh0Uk1HU2p5Z1pTdkxFVUVtdlhVWGZCQUIzaVRRNE14RFRVbkNkdjBtS1BBb0dBZm9ZOQpOZzNXR0QrbkJ4NkVxWUppcHVCblZnM3U2UXRRNHl6aXRkeG8vZTBHY2g1TEVkUTI3TEYydHcyOFRmektKd3RlCmx4aFRCNmxnQ1dNQ1Z4NTN1NktKZEtNQXhyY3FZRTI1ZEFMd09XZW52N0xxNVpvNWE0MjhzYUo2WGVrSGdPRDAKL3haa2hVNkRUNzVDamVWcS9Bek1VdTVhM3ZGdTdjak5YcHFtTjdVQ2dZQWlhRTRlSkRydkc1K1F1ZGY3bS9JbAplSHQ1dXBzZnZuaHVrdzAxWjdOYnIxY2J4N1lRaFZzQ1Y0cG94bXUvcWIwU0x5a3hjbktxa1BUMDFMODQyNFVvCkhtOVpETXF5b3BSbmprWjNaSDFxK2ZSM1hyeE9sUnF5aGdjMlMrZExVRkdCdVBBdE5QOGU2cVBCSVNZVXp3Q0oKYVdtL0xiOWJ5MkJMYUhKOEZ5QmZNQT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook
webhooks:
  - name: validate.default.svc
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1","v1beta1"]
    rules:
      - apiGroups: ["apps", ""]
        resources:
          - "deployments"
        apiVersions:
          - "*"
        operations:
          - CREATE
    clientConfig:
      service:
        name: validate
        namespace: default
        path: /validate/
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVHakNDQXdLZ0F3SUJBZ0lVY1hUWmRiZHdCQjB3d0ZqeGdoZElLSEFDK21zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZc3hDekFKQmdOVkJBWVRBa2xPTVFzd0NRWURWUVFJREFKTFFURVFNQTRHQTFVRUJ3d0hWVTVMVGs5WApUakVOTUFzR0ExVUVDZ3dFVTBWTVJqRU5NQXNHQTFVRUN3d0VVMFZNUmpFV01CUUdBMVVFQXd3TloyOTJhVzVrCllYSmhhbUZ1ZGpFbk1DVUdDU3FHU0liM0RRRUpBUllZWjI5MmFXNWtZWEpoYW1GdWRrQm5hWFJvZFdJdVkyOXQKTUI0WERUSXpNVEF3T0RFeU1qSTFPVm9YRFRJMk1EY3lPREV5TWpJMU9Wb3dnWXN4Q3pBSkJnTlZCQVlUQWtsTwpNUXN3Q1FZRFZRUUlEQUpMUVRFUU1BNEdBMVVFQnd3SFZVNUxUazlYVGpFTk1Bc0dBMVVFQ2d3RVUwVk1SakVOCk1Bc0dBMVVFQ3d3RVUwVk1SakVXTUJRR0ExVUVBd3dOWjI5MmFXNWtZWEpoYW1GdWRqRW5NQ1VHQ1NxR1NJYjMKRFFFSkFSWVlaMjkyYVc1a1lYSmhhbUZ1ZGtCbmFYUm9kV0l1WTI5dE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXJGU2doSDBvQ3ZLdVFLUWIrWjFmOTJFazIvM0F5NTFzR0xKQmRCMnROVXhFCjNWWkQ4YjM4UVRpSU5NRmtNWjFhbjhqdUtCeGw4NmJBNEpJdDVPTzJFbXJRR1JpWk44UjZSbE52OUFvK2ovdVAKb1B1TWs3ZjAxRDQrVGZld2pOZUJZWW1RNHNMMTZCS3QyWWlROHoyekFCeHBvcGhPbEkyczE1Nm5JSzJhQkdLUwp1SVYxcERkdC9xbTcxTzZ0N2tKajVDalN2MmZMNGxJZmNwTk5PT1MvQlRGZlpwQmwxK21waEVYK0dJL3g5ZWo0CkIxMlBYTUtYaVdWSEMxRzY4cUZHOEpjNVpUbldndkN3UTJPRFRtVWNzdGxwc0U1Wnp4SDdzUlpXZ1d3TVBRVEsKUGFqcTVVVXhScHdYNXMwS09SSlNuQWw1UnNEK21qQmN0VUY1R2NKWDFRSURBUUFCbzNRd2NqQWRCZ05WSFE0RQpGZ1FVaUVzNkFiWXBPbExzTUxadWpubkVZMGFTRzA0d0h3WURWUjBqQkJnd0ZvQVVpRXM2QWJZcE9sTHNNTFp1CmpubkVZMGFTRzA0d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZkJnTlZIUkVFR0RBV2doUjJZV3hwWkdGMFpTNWsKWldaaGRXeDBMbk4yWXpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQXBNRmtQK1gyMjNTeHVFZEQrRGNqcGtTQwptNmhYNjAyMnNDT1UvdHFIY0N1MVl5NWhMUUNCTFBNTnZyZFozKzFkK05PamhYcFUzQ01mL2Vtd0xNQUFYWDlVClhBLzJEd1BhLzIzbk4vbE5BTGhlWkZoZ3lPUmJOZTlZUHVmeDh2UDRHWWs4V1cxcnV0V3V3Mnd6cTVBM0dJSmEKQWV5VXZyZHZnc2xwZVNxSlNNNWx4OFl5dXZGZFo0REMveis1QzZxd3dZZnFuV1FZelNSZThmeVNCNjZCT0VweQpkazR1MUFJYVFmYzgrZnExbHVDa1FIUzZnOWRsSDd2RGFBbGp2cVR2dzJyUTdrRXQ4bkE4cWNnMkdiL3NVb0s3Cm53WlBUVU1ZUWZXZS9VcTRRWTJ2NFJWRzVsSGc0SUFLMWZ2c3NyTStaSEZPam8vNHoxSTVud2R1czI4b3NRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=